name: Nix Linters

on:
  push:
    paths:
      - '**/*.nix'
      - flake.lock
      - flake.nix
  pull_request:
    paths:
      - '**/*.nix'
      - flake.lock
      - flake.nix
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: statix & deadnix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11

      - name: Setup magic cache
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Run statix & deadnix
        run: ./scripts/run-lints.sh
